import type {
  Activity,
  ActivityCourt,
  Club,
  ClubMember,
  Registration,
  RegistrationLog,
  UserProfile,
  Venue,
  VenueCourt,
} from "../types/activity";

export type ActivityStore = {
  users: UserProfile[];
  venues: Venue[];
  venueCourts: VenueCourt[];
  clubs: Club[];
  clubMembers: ClubMember[];
  activities: Activity[];
  activityCourts: ActivityCourt[];
  registrations: Registration[];
  registrationLogs: RegistrationLog[];
};

const store: ActivityStore = {
  users: [
    {
      id: "user-current",
      nickname: "小陈",
      gender: "MALE",
      avatarColor: "#4C7CF0",
      baseProfileComplete: true,
    },
    { id: "user-lin", nickname: "林北", gender: "MALE", avatarColor: "#43B581" },
    { id: "user-ava", nickname: "Ava", gender: "FEMALE", avatarColor: "#FF8A65" },
    { id: "user-zoe", nickname: "Zoe", gender: "FEMALE", avatarColor: "#A66BFF" },
    { id: "user-neo", nickname: "Neo", gender: "MALE", avatarColor: "#FFB547" },
    { id: "user-mia", nickname: "Mia", gender: "FEMALE", avatarColor: "#E56DAA" },
  ],
  venues: [
    {
      id: "venue-jinqiao",
      name: "浦东金桥羽毛球馆",
      shortName: "金桥馆",
      province: "上海市",
      city: "上海市",
      district: "浦东新区",
      address: "金桥路 588 号 B1",
      latitude: 31.2572,
      longitude: 121.6073,
      navigationName: "浦东金桥羽毛球馆",
      status: "ACTIVE",
    },
    {
      id: "venue-minhang",
      name: "闵行星跃球馆",
      shortName: "星跃馆",
      province: "上海市",
      city: "上海市",
      district: "闵行区",
      address: "申虹路 1188 号 3 层",
      latitude: 31.2011,
      longitude: 121.3248,
      navigationName: "闵行星跃球馆",
      status: "ACTIVE",
    },
  ],
  venueCourts: [
    {
      id: "court-jinqiao-1",
      venueId: "venue-jinqiao",
      courtCode: "1",
      courtName: "1 号场",
      sortOrder: 1,
      status: "ACTIVE",
    },
    {
      id: "court-jinqiao-2",
      venueId: "venue-jinqiao",
      courtCode: "2",
      courtName: "2 号场",
      sortOrder: 2,
      status: "ACTIVE",
    },
    {
      id: "court-jinqiao-3",
      venueId: "venue-jinqiao",
      courtCode: "3",
      courtName: "3 号场",
      sortOrder: 3,
      status: "ACTIVE",
    },
    {
      id: "court-minhang-a",
      venueId: "venue-minhang",
      courtCode: "A",
      courtName: "A 场",
      sortOrder: 1,
      status: "ACTIVE",
    },
    {
      id: "court-minhang-b",
      venueId: "venue-minhang",
      courtCode: "B",
      courtName: "B 场",
      sortOrder: 2,
      status: "ACTIVE",
    },
    {
      id: "court-minhang-c",
      venueId: "venue-minhang",
      courtCode: "C",
      courtName: "C 场",
      sortOrder: 3,
      status: "ACTIVE",
    },
  ],
  clubs: [
    {
      id: "club-penguin",
      name: "企鹅羽球俱乐部",
      contactName: "阿鹏",
      contactPhone: "13912345678",
      status: "ACTIVE",
    },
    {
      id: "club-rally",
      name: "Rally 周末局",
      contactName: "Mia",
      contactPhone: "13700001111",
      status: "ACTIVE",
    },
  ],
  clubMembers: [
    { id: "member-1", clubId: "club-penguin", userId: "user-current", role: "OWNER" },
    { id: "member-2", clubId: "club-penguin", userId: "user-lin", role: "ADMIN" },
    { id: "member-3", clubId: "club-penguin", userId: "user-ava", role: "MEMBER" },
    { id: "member-4", clubId: "club-rally", userId: "user-current", role: "ADMIN" },
  ],
  activities: [
    {
      id: "activity-apr-02",
      ownerType: "CLUB",
      ownerId: "club-penguin",
      createdBy: "user-current",
      ownerDisplay: {
        mode: "CLUB",
        name: "企鹅羽球俱乐部",
        contactName: "阿鹏",
        contactWechat: "penguin-apeng",
      },
      title: "周三晚场双打局",
      chargeMode: "FIXED",
      chargeAmountCents: 6800,
      chargeDesc: "含场地和球，共 2 小时",
      venueId: "venue-jinqiao",
      venueSnapshotName: "浦东金桥羽毛球馆",
      activityStartAt: "2026-04-16T19:30:00+08:00",
      activityEndAt: "2026-04-16T21:30:00+08:00",
      cancelCutoffMinutesBeforeStart: 120,
      cancelDeadlineAt: "2026-04-16T17:30:00+08:00",
      descriptionRichtext:
        "适合 3.0-4.0 球友，默认双打轮转。报名时直接选场，现场可由管理员调整到其他场地。",
      signupMode: "USER_SELECT_COURT",
      status: "PUBLISHED",
    },
    {
      id: "activity-apr-05",
      ownerType: "PERSONAL",
      ownerId: "user-current",
      createdBy: "user-current",
      ownerDisplay: {
        mode: "PERSONAL",
        name: "小陈",
        avatarColor: "#4C7CF0",
        contactName: "小陈",
        contactWechat: "xc-badminton",
      },
      title: "周末轻松娱乐局",
      chargeMode: "AA",
      chargeAmountCents: 4500,
      chargeDesc: "按实到 AA，多退少补",
      venueId: "venue-minhang",
      venueSnapshotName: "闵行星跃球馆",
      activityStartAt: "2026-04-19T14:00:00+08:00",
      activityEndAt: "2026-04-19T17:00:00+08:00",
      cancelCutoffMinutesBeforeStart: 60,
      cancelDeadlineAt: "2026-04-19T13:00:00+08:00",
      descriptionRichtext: "新手友好，鼓励带朋友一起来，活动结束后可一键再次发布。",
      signupMode: "USER_SELECT_COURT",
      status: "PUBLISHED",
    },
    {
      id: "activity-apr-08",
      ownerType: "CLUB",
      ownerId: "club-rally",
      createdBy: "user-current",
      ownerDisplay: {
        mode: "CLUB",
        name: "Rally 周末局",
        contactName: "Mia",
        contactWechat: "rally-mia",
      },
      title: "周中 36 人大组局",
      chargeMode: "AA",
      chargeAmountCents: 0,
      chargeDesc: "活动结束后按实到 AA 分摊",
      venueId: "venue-jinqiao",
      venueSnapshotName: "浦东金桥羽毛球馆",
      activityStartAt: "2026-04-22T19:00:00+08:00",
      activityEndAt: "2026-04-22T22:00:00+08:00",
      cancelCutoffMinutesBeforeStart: 120,
      cancelDeadlineAt: "2026-04-22T17:00:00+08:00",
      descriptionRichtext: "统一分配，不预先分场地，活动开始前由管理员线下统一编排。",
      signupMode: "GENERAL",
      totalCapacity: 36,
      status: "PUBLISHED",
    },
  ],
  activityCourts: [
    {
      id: "activity-court-1",
      activityId: "activity-apr-02",
      venueCourtId: "court-jinqiao-1",
      courtCodeSnapshot: "1",
      courtNameSnapshot: "1 号场",
      capacity: 4,
      sortOrder: 1,
      status: "ACTIVE",
    },
    {
      id: "activity-court-2",
      activityId: "activity-apr-02",
      venueCourtId: "court-jinqiao-2",
      courtCodeSnapshot: "2",
      courtNameSnapshot: "2 号场",
      capacity: 4,
      sortOrder: 2,
      status: "ACTIVE",
    },
    {
      id: "activity-court-3",
      activityId: "activity-apr-05",
      venueCourtId: "court-minhang-a",
      courtCodeSnapshot: "A",
      courtNameSnapshot: "A 场",
      capacity: 4,
      sortOrder: 1,
      status: "ACTIVE",
    },
    {
      id: "activity-court-4",
      activityId: "activity-apr-05",
      venueCourtId: "court-minhang-b",
      courtCodeSnapshot: "B",
      courtNameSnapshot: "B 场",
      capacity: 4,
      sortOrder: 2,
      status: "ACTIVE",
    },
  ],
  registrations: [
    {
      id: "registration-1",
      activityId: "activity-apr-02",
      userId: "user-lin",
      activityCourtId: "activity-court-1",
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-28T11:00:00+08:00",
    },
    {
      id: "registration-2",
      activityId: "activity-apr-02",
      userId: "user-ava",
      activityCourtId: "activity-court-1",
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-28T11:30:00+08:00",
    },
    {
      id: "registration-3",
      activityId: "activity-apr-02",
      userId: "user-neo",
      activityCourtId: "activity-court-1",
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-28T12:00:00+08:00",
    },
    {
      id: "registration-4",
      activityId: "activity-apr-02",
      userId: "user-current",
      activityCourtId: "activity-court-1",
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-28T12:30:00+08:00",
    },
    {
      id: "registration-5",
      activityId: "activity-apr-02",
      userId: "user-mia",
      activityCourtId: "activity-court-1",
      signupStatus: "WAITLIST",
      queueNo: 1,
      createdAt: "2026-03-28T13:00:00+08:00",
    },
    {
      id: "registration-6",
      activityId: "activity-apr-05",
      userId: "user-zoe",
      activityCourtId: "activity-court-3",
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-28T10:40:00+08:00",
    },
    {
      id: "registration-7",
      activityId: "activity-apr-08",
      userId: "user-lin",
      activityCourtId: null,
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-29T10:00:00+08:00",
    },
    {
      id: "registration-8",
      activityId: "activity-apr-08",
      userId: "user-ava",
      activityCourtId: null,
      signupStatus: "CONFIRMED",
      createdAt: "2026-03-29T10:10:00+08:00",
    },
  ],
  registrationLogs: [],
};

export function getActivityStore(): ActivityStore {
  return store;
}
